# Torch vs. Numpy

In [2]:
import torch
import numpy as np

## Bridge between torch and numpy

In [8]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

In [38]:
print(
    '\n--- numpy array ---\n', np_data,          
    '\n--- torch tensor ---\n', torch_data,     
    '\n--- tensor to array ---\n', tensor2array, 
)


--- numpy array ---
 [[0 1 2]
 [3 4 5]] 
--- torch tensor ---
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
--- tensor to array ---
 [[0 1 2]
 [3 4 5]]


## Operations

In [44]:
# matrix multiplication 
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 转换成32位浮点 tensor
# correct method
print(
    '\n--- matrix multiplication (@) ---',     # [[7, 10], [15, 22]]
    '\n numpy \n', np.matmul(data, data),     # Or np.dot(data, data)
    '\n torch \n', torch.mm(tensor, tensor)   
)

# !!!!  Wrong method !!!!
# data = np.array(data)
# print(
#     '\nmatrix multiplication (dot)',
#     '\nnumpy: ', data.dot(data),        # numpy works
#     '\ntorch: ', torch.dot(tensor.dot(tensor))     # NOT WORKING! Beware that torch.dot does not broadcast, only works for 1-dimensional tensor
# )

# matirx dot multiplication
print(
    '\n--- matrix  multiplication (*) ---',
    '\n numpy \n', np.multiply(data, data), 
    '\n torch \n', tensor * tensor
)


--- matrix multiplication (@) --- 
 numpy 
 [[ 7 10]
 [15 22]] 
 torch 
 tensor([[ 7., 10.],
        [15., 22.]])

--- matrix  multiplication (*) --- 
 numpy 
 [[ 1  4]
 [ 9 16]] 
 torch 
 tensor([[ 1.,  4.],
        [ 9., 16.]])


## Tensor vs. Variable

In [47]:
import torch
from torch.autograd import Variable

In [50]:
tensor = torch.FloatTensor([[1,2],[3,4]])            # build a tensor
variable = Variable(tensor, requires_grad=True)      # build a variable, usually for compute gradients

print(tensor)       # [torch.FloatTensor of size 2x2]
print(variable)     # [torch.FloatTensor of size 2x2]

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [51]:
t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


In [52]:
v_out.backward()    # backpropagation from v_out
# v_out = 1/4 * sum(variable*variable) 
# d(v_out)/d(variable) = 1/4*2*variable = variable/2

 $V_{out} = \frac{1}{4}\cdot \sum_{i=1}^{4}v_{i}\cdot v_{i} $
 
 $ \frac{\partial{V_{out}}}{\partial{v}} = 1/4\cdot2\cdot v = \frac{v}{2} $

In [58]:
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [59]:
print(variable) # this is data in variable format
print(variable.data) # this is data in tensor format
print(variable.data.numpy()) # numpy format

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
